import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import localFont from "next/font/local";
import Nav from "@/components/Nav";

const workSans = Work_Sans({ subsets: ["latin"] });

const saint = localFont({
  src: [
    {
      path: "./fonts/SaintRegular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-saint",
});

const bebasNeue = localFont({
  src: [
    {
      path: "./fonts/BebasNeue-Regular.woff2",
    },
  ],
  variable: "--font-bebas",
});

const destra = localFont({
  src: [
    {
      path: "./fonts/GPDestra-Light.otf",
      weight: "400",
    },
  ],
  variable: "--font-destra",
});

const honey = localFont({
  src: [
    {
      path: "./fonts/HoneyDemo-Light.otf",
      weight: "400",
    },
  ],
  variable: "--font-honey",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${saint.variable} ${bebasNeue.variable} ${destra.variable} ${honey.variable}`}>
      <body
        className={`${workSans.className} ${honey.variable} ${destra.variable} ${bebasNeue.variable}`}>
        <div className="bg-[#dfdfdf]">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
