import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import localFont from "next/font/local";

const workSans = Work_Sans({ subsets: ["latin"] });

const saint = localFont({
  src: [
    {
      path: "../public/fonts/SaintRegular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-saint",
});

const bebasNeue = localFont({
  src: [
    {
      path: "../public/fonts/BebasNeue-Regular.woff2",
      weight: "400",
    },
  ],
  variable: "--font-bebas",
});

const destra = localFont({
  src: [
    {
      path: "../public/fonts/GPDestra-Light.otf",
      weight: "400",
    },
  ],
  variable: "--font-destra",
});

const honey = localFont({
  src: [
    {
      path: "../public/fonts/HoneyDemo-Light.otf",
      weight: "400",
    },
  ],
  variable: "--font-honey",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${saint.variable} ${bebasNeue.variable} ${destra.variable} ${honey.variable}`}
    >
      <body
        className={`${workSans.className} ${honey.variable} ${destra.variable} ${bebasNeue.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
